name: models
description: A package for holding api/dto/app model types 
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  
dependencies:  
  built_collection: ^5.1.1
  built_value: ^8.5.0
  intl: ^0.18.1
  
dev_dependencies:
  build_runner:
  built_value_generator: ^8.5.0
  injectable_generator: ^2.1.5
  very_good_analysis: ^3.0.1
